uwsgi:
  image: "${DOCKER_USER}/pixelgroup-home-uwsgi:${CIRCLE_SHA1}"
  container_name: ${CIRCLE_BUILD_NUM}_uswgi_1
nginx:
  image: "${DOCKER_USER}/pixelgroup-home-nginx:${CIRCLE_SHA1}"
  container_name: ${CIRCLE_BUILD_NUM}_nginx_1
  links:
    - uwsgi
  ports:
    - "${NGINX_PORT}"
